### ISSUE TITLE
Instagram phishlet doesn't load images

### ISSUE THREAD

**Issue by LarmonH** [charlesbel/Evilginx2-Phishlets#2]
I can successfully capture session cookies and use them to hijack a session on the attacker machine, but the victim sees this:
![instagramScreenshot](https://user-images.githubusercontent.com/66245102/154359925-b2003a89-eb2b-4299-aeef-0e6fcb15118f.png)
@charlesbel

**Comment by LarmonH** [comment]
I would like to add that I've already created A records for:
img.instagram.myDomain.com
graphql.instagram.myDomain.com
i.instagram.myDomain.com
and www.instagram.myDomain.com
where myDomain is the name of the domain I've purchased and connected to DigitalOcean.

**Comment by rzmpzgeviii** [comment]
did you manage to fix this? Got the same problem

**Comment by charlesbel** [comment]
Fixed
