### ISSUE TITLE
There was a problem logging you into Instagram :(

### ISSUE THREAD

**Issue by rzmpzgeviii** [charlesbel/Evilginx2-Phishlets#3]
"There was a problem logging you into instagram. Please try again soon"

The console registers username and password but no token  and the victim sees this instagram error page:
![1](https://user-images.githubusercontent.com/101715188/198045003-99c985ea-a3f7-4bc9-b623-8e130f0ad9d0.PNG)

Any idea how to troubleshoot? What could be the reason?

**Comment by charlesbel** [comment]
Fixed
