### ISSUE TITLE
Instagram phishlet didnt catch otp

### ISSUE THREAD

**Issue by theredbruno** [charlesbel/Evilginx2-Phishlets#4]
![1E5180B3-5CE3-4905-A0EF-A6749E37F944](https://user-images.githubusercontent.com/99856896/222959113-10218c9e-18b0-4fb3-82d2-3aa5c6db69eb.png)

After clicking on login on the Instagram page, it gives an error “there was a problem logging you in, please try again later” have tried many times but it still gives that error, other credentials caught except from otp, Anybody got any ideas for help on this pls?

**Comment by charlesbel** [comment]
IP related, can't do anything for that
