### ISSUE TITLE
Instagram Page not responsing 

### ISSUE THREAD

**Issue by fbracon** [charlesbel/Evilginx2-Phishlets#5]
![Screenshot (9)](https://user-images.githubusercontent.com/63225245/227681898-1995ec41-2f4d-4afa-acba-a6a24e238dde.png)

**Comment by charlesbel** [comment]
> ![Screenshot (9)](https://user-images.githubusercontent.com/63225245/227681898-1995ec41-2f4d-4afa-acba-a6a24e238dde.png)
> 

Please show network tab of your Web browser so we can check requests made by your browser

**Comment by Cobrasyf** [comment]
Yeah i am having the exact same problem.. The network tab just shows the url containing the domain name, but is followed with accounts/login/ 

like here:
https://www.instatest.com/accounts/login/

**Comment by Cobrasyf** [comment]
Yeah i am having exact same problem.. i just opened network tab in firefox and in the bottom is stated a warning:

<script> source URI is not allowed in this document: “https://static-cdn.mydomain.com/rsrc.php/v3idBq4/yE/l/en_US/V75SokU2SRZ.js?_nc_x=Ij3Wp8lg5Kz”.

**Comment by Cobrasyf** [comment]
i think its about the static-cdn
it is also showing this:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static-cdn.mydomain.com/rsrc.php/v3/y-/l/0,cross/y_UO-KemfyjKZUO4Ellim8.css?_nc_x=Ij3Wp8lg5Kz. (Reason: CORS request did not succeed). Status code: (null).

**Comment by fbracon** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/63225245/227743478-a263b3c7-a79c-4ab7-a0d9-369cd20b3423.png)
![Screenshot (12)](https://user-images.githubusercontent.com/63225245/227743492-18a84247-b684-4a61-bcb1-8d661493f48d.png)

**Comment by charlesbel** [comment]
> ![Screenshot (13)](https://user-images.githubusercontent.com/63225245/227743478-a263b3c7-a79c-4ab7-a0d9-369cd20b3423.png)
> ![Screenshot (12)](https://user-images.githubusercontent.com/63225245/227743492-18a84247-b684-4a61-bcb1-8d661493f48d.png)
> 

You just need to setup correctly the subdomains required according to the phishlet

**Comment by fbracon** [comment]
This is my fault .. The problem was really in setup of subdomains .. Thanks for the quick reply

**Comment by Cobrasyf** [comment]
hey fbracon, did you fix it? Where do you setup the subdomains?

**Comment by Cobrasyf** [comment]
like where/how did you exactly resolve the issue? i cant cuite figure where

**Comment by Cobrasyf** [comment]
@fbracon Does the instagram phish work for you?

**Comment by fbracon** [comment]
@Cobrasyf page is working .. seems the same of mine .. you need only setup your subdomains again and do not forget to add the new subdomains (static-cdn)
