### ISSUE TITLE
Instagram not working?

### ISSUE THREAD

**Issue by Cobrasyf** [charlesbel/Evilginx2-Phishlets#6]
hi. i am having an issue where the site wont get to the login page. i have checked everything including my subdomains, but everything seems correct. this is the message i get when i open network tab:

“https://static-cdn.mydomain.com/rsrc.php/v3idBq4/yE/l/en_US/V75SokU2SRZ.js?_nc_x=Ij3Wp8lg5Kz”. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static-cdn.mydomain.com/rsrc.php/v3/y-/l/0,cross/y_UO-KemfyjKZUO4Ellim8.css?_nc_x=Ij3Wp8lg5Kz. (Reason: CORS request did not succeed). Status code: (null).

**Comment by Cobrasyf** [comment]
@charlesbel

**Comment by fbracon** [comment]
@Cobrasyf  try to setup your subdomains correctly and do not forget to add the net subdomains ( static-cdn)

**Comment by charlesbel** [comment]
Certificate issue, delete them from evilginx and generate new ones that will include new domains
